import type { Metadata } from "next";
import Link from "next/link";
import LegalLayout, { LegalSection } from "@/components/legal/LegalLayout";
import { site } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `Terms of Service for ${site.name}.`,
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" currentPath="/terms">
      <LegalSection number="01" title="Who these terms apply to">
        <p>
          {site.name} is operated by {site.founder} as a sole operator. These
          terms cover the website, the application process, and any engagement
          that follows.
        </p>
      </LegalSection>

      <LegalSection number="02" title="Applications">
        <p>
          Submitting an application does not create a working relationship and
          does not oblige me to respond. I personally read every application
          received. I will only reach out if I believe there is a genuine fit to
          work together. If you do not hear back, it means I did not think I was
          the right person for your brand at that time, and it is not a judgement
          of your business. I am under no obligation to give feedback or a
          reason. Information you submit must be accurate and yours to share.
          Spots are limited and taken on a first come, first served basis,
          subject to my assessment of fit.
        </p>
      </LegalSection>

      <LegalSection number="03" title="Services">
        <p>
          Two engagement types. Lane A covers creators and digital brands:
          building digital products and rebuilding store and sales pages, scaled
          through the client&apos;s own social presence. Lane B covers physical
          product brands: storefront rebuilds and conversion work. The specific
          scope of any engagement is set out in a separate written agreement
          between the parties. These terms are the general framework, and where
          the two conflict the separate agreement governs.
        </p>
      </LegalSection>

      <LegalSection number="04" title="Fees">
        <p>
          Lane A runs on a revenue split, an agreed percentage of revenue
          generated by the product built, with no upfront fee. Lane B runs on a
          flat monthly retainer billed in advance. Exact percentages, amounts,
          billing dates and payment methods are agreed in writing before work
          begins. Fees are non refundable except where the law requires
          otherwise.
        </p>
      </LegalSection>

      <LegalSection number="05" title="Term and termination">
        <p>
          Engagements continue while the agreed fee is being paid. Either party
          may end an engagement with written notice as set out in the separate
          agreement. I may end an engagement immediately for non payment, or for
          conduct that is abusive, unlawful, or that would damage either
          party&apos;s reputation.
        </p>
      </LegalSection>

      <LegalSection number="06" title="What happens when payment stops">
        <p>
          This section is important, so read it carefully. If payment stops,
          ends or lapses for any reason, then from that date:
        </p>
        <ul className="list-disc space-y-3 pl-5">
          <li>
            You keep everything already built and delivered up to the end of the
            final paid period. It stays live and it is yours to use.
          </li>
          <li>
            All work stops immediately. No further updates, edits, revisions,
            fixes, optimisations, redesigns, additions or changes of any kind
            will be made to your product, site, storefront or funnel.
          </li>
          <li>
            Ongoing maintenance, hosting, security updates, platform and
            dependency updates, bug fixes and any future development become your
            sole responsibility. I am not responsible for anything that breaks,
            degrades or stops working after the engagement ends.
          </li>
          <li>
            No further changes to your personal brand site will be made by me.
            Any development after that point is entirely down to you or someone
            you appoint.
          </li>
          <li>
            No support, consultation or assistance is included after the final
            paid period.
          </li>
          <li>
            Resuming work after a lapse requires a new written agreement and is
            subject to my availability, updated terms and updated rates.
          </li>
        </ul>
      </LegalSection>

      <LegalSection number="07" title="Ownership">
        <p>
          On full payment for the relevant period you own the final delivered
          work: the copy, design, product content and page builds created
          specifically for your brand. I keep ownership of the underlying
          methods, frameworks, templates, reusable components and know how used
          to produce it, and I stay free to reuse those on other engagements.
          Third party assets such as fonts, platforms, plugins and hosting remain
          governed by their own licences, and maintaining those is your
          responsibility once the engagement ends.
        </p>
      </LegalSection>

      <LegalSection number="08" title="Systems and database access">
        <p>
          During an engagement I build and administer systems on your behalf,
          which may include databases, content management systems, analytics,
          email tooling and hosting accounts. I keep continued administrative
          access to these systems, including after an engagement ends, for
          technical, archival and continuity reasons. You may ask in writing at{" "}
          <a
            href={`mailto:${site.email}`}
            className="text-accent underline-offset-2 hover:underline"
          >
            {site.email}
          </a>{" "}
          for that access to be revoked and I will remove it within a reasonable
          period. Once access is revoked I cannot restore, migrate, recover or
          assist with those systems at any point in future. Where such a system
          holds personal data belonging to your own customers, you remain the
          data controller and I act as a processor on your instructions, and you
          may request deletion of that data at any time. See the{" "}
          <Link
            href="/privacy"
            className="text-accent underline-offset-2 hover:underline"
          >
            Privacy Policy
          </Link>{" "}
          for detail.
        </p>
      </LegalSection>

      <LegalSection number="09" title="Your responsibilities">
        <p>
          Providing timely access, assets, brand materials, approvals and
          feedback. Reviewing at the agreed checkpoints. Making sure anything
          you supply is lawful and yours to use. Making sure your product,
          claims, pricing and business comply with applicable law. Delays in
          providing what is needed will extend timelines.
        </p>
      </LegalSection>

      <LegalSection number="10" title="No guarantee of results">
        <p>
          I do not guarantee any specific revenue, conversion rate, follower
          growth, sales volume or business outcome. See the{" "}
          <Link
            href="/disclaimer"
            className="text-accent underline-offset-2 hover:underline"
          >
            Results and Earnings Disclaimer
          </Link>
          .
        </p>
      </LegalSection>

      <LegalSection number="11" title="Confidentiality">
        <p>
          Each party keeps the other&apos;s non public business information
          confidential and uses it only for the engagement. I may reference the
          work publicly as a portfolio piece or case study unless you ask me in
          writing not to.
        </p>
      </LegalSection>

      <LegalSection number="12" title="Limitation of liability">
        <p>
          To the maximum extent the law allows, my total liability arising from
          an engagement is limited to the total fees you paid me in the three
          months immediately before the event giving rise to the claim. I am not
          liable for indirect, incidental or consequential losses, including
          lost profits, lost revenue, lost data or business interruption.
          Nothing here limits liability that cannot lawfully be limited.
        </p>
      </LegalSection>

      <LegalSection number="13" title="Changes to these terms">
        <p>
          These terms may be updated and the last updated date at the top will
          change. Material changes affecting an active engagement will be
          communicated directly. Continuing to use the site means accepting the
          current version.
        </p>
      </LegalSection>

      <LegalSection number="14" title="Governing law">
        <p>
          The governing law is set out in the separate written agreement for
          each engagement.
        </p>
        {/* TODO: Daive, insert your governing jurisdiction and courts here */}
      </LegalSection>

      <LegalSection number="15" title="Contact">
        <p>
          Questions about these terms:{" "}
          <a
            href={`mailto:${site.email}`}
            className="text-accent underline-offset-2 hover:underline"
          >
            {site.email}
          </a>
          .
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
